            - name: Streamlit App Action
  # You may pin to the exact commit or the version.
  # uses: streamlit/streamlit-app-action@d1a3fbb4e96e28167fc4d8714c740ac21012bad5
  uses: streamlit/streamlit-app-action@v0.0.3
  with:
    # Filepath to the main app file (`streamlit run <this>`)
    app-path: # optional, default is streamlit_app.py
    # Run ruff linting
    ruff: # optional, default is false
    # Command line arguments to pass to pytest
    pytest-args: # optional, default is -v
    # Skip the provided smoke test. Useful if your app testing requires advanced setup.
    skip-smoke: # optional, default is false
          
